
version: '3'

services:
  # Web UI for proxy management
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    environment:
      - NGINX_CONFIG_PATH=/etc/nginx/nginx.conf
      - AUTH_TYPE=${AUTH_TYPE:-none}
      - LDAP_SERVER=${LDAP_SERVER:-}
      - LDAP_PORT=${LDAP_PORT:-389}
      - LDAP_USE_SSL=${LDAP_USE_SSL:-false}
      - LDAP_BIND_DN=${LDAP_BIND_DN:-}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE:-}
      - LDAP_SEARCH_FILTER=${LDAP_SEARCH_FILTER:-}
      - CLIENT_AUTH_REQUIRED=${CLIENT_AUTH_REQUIRED:-false}
      - CLIENT_AUTH_METHOD=${CLIENT_AUTH_METHOD:-none}
      - CLIENT_AUTH_REALM=${CLIENT_AUTH_REALM:-Proxy Access}
    volumes:
      - nginx_config:/etc/nginx
    networks:
      - proxy-network
    depends_on:
      - nginx-proxy

  # Nginx proxy service
  nginx-proxy:
    build:
      context: ./nginx
    ports:
      - "${PROXY_PORT:-8080}:8080"
    volumes:
      - nginx_config:/etc/nginx
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:

volumes:
  nginx_config:
